modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "satchels"
version = "${version}"
displayName = "Satchels"
authors = "Vercte"
description = '''
another kind of inventory expansion
'''
#logoFile = ""

[[dependencies.satchels]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.satchels]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.satchels]]
modId = "curios"
type = "required"
versionRange = "[9.2.0+1.21.1, 10.0.0+1.21.1)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "satchels.mixins.json"

[[mixins]]
config = "satchels-neoforge.mixins.json"
