modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "satchels"
version = "${version}"
displayName = "Satchels"
authors = "Vercte"
description = '''
satcheling it
'''
#logoFile = ""

[[dependencies.satchels]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.satchels]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "satchels.mixins.json"
